import { FC, useEffect, useState } from 'react'
import { useLocation } from 'react-router-dom'

import DynamicForm from '../../../../components/dynamicForm'
import { FormConfigure } from '../../../../components/types/dynamicForm'

const configuration: FormConfigure = {
    pathname: '/configuracion/usuarios',
    titles: {
        all: 'Lista de usuarios',
        create: 'Creación de usuario',
        edit: 'Actualización de usuario',
        view: 'Información del usuario',
        delete: 'Información del usuario',
    },
    type: 'drawer', //tabs, modal, drawer
    data: [
        {
            name: 'name',
            type: 'string',
            label: 'Primer nombre',
            props: {
                required: true,
                placeholder: 'Escribe el primer nombre',
                maxLenght: 50,
            },
        },
        {
            name: 'second_name',
            type: 'string',
            label: 'Segundo nombre',
            props: {
                placeholder: 'Escribe el segundo nombre',
                maxLenght: 50,
            },
        },
        {
            name: 'last_name',
            type: 'string',
            label: 'Primer apellido',
            props: {
                required: true,
                placeholder: 'Escribe el primer apellido',
                maxLenght: 50,
            },
        },
        {
            name: 'second_last_name',
            type: 'string',
            label: 'Segundo apellido',
            props: {
                placeholder: 'Escribe el segundo apellido',
                maxLenght: 50,
            },
        },
    ],
    entity: 'users',
    mode: 'default',
}
const information = [
    {
        id: 1,
        name: 'Juan',
        second_name: 'Camilo',
        last_name: 'Arbelaez',
        second_last_name: 'Ordoñez',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
    {
        id: 2,
        name: 'Sara',
        second_name: 'Melissa',
        last_name: 'Mosquera',
        second_last_name: 'Galarza',
        identification_id: 2,
        identification_number: '1112791775',
        birthday: '1998-06-25',
    },
]
const DynamicPage: FC = () => {
    const { pathname } = useLocation()
    const [config] = useState<FormConfigure>(configuration)
    const [data] = useState(information)

    useEffect(() => {
        console.log(pathname)
    }, [])
    return (
        <div
            className='p-4 bg-white border border-gray-200 rounded-lg shadow-sm  dark:border-gray-700 sm:p-6 dark:bg-gray-800'
            style={{ minHeight: 'calc(100vh - 228px)' }}
        >
            <h1 className='text-lg font-semibold text-gray-900 sm:text-xl dark:text-white mb-2'>
                Dynamic page
            </h1>
            <DynamicForm data={data} config={config} />
        </div>
    )
}

export default DynamicPage
